[package]
name = "genuary"
edition = "2024"

[dependencies]
bevy = {version = "0.17.3", features = ["file_watcher", "jpeg"]}
bevy_math = "0.17.3"
image = "0.25.9"
noiz = "0.3.0"

[[bin]]
name = "day2"
path = "src/day2.rs"

[[bin]]
name = "day3"
path = "src/day3.rs"
